set -ga terminal-overrides ",screen-256color*:Tc"
set-option -g default-terminal "screen-256color"
set -s escape-time 0

# Set prefix to Ctrl+q
unbind C-b
set-option -g prefix C-q
bind-key C-q send-prefix

# Styling
set -g status-style 'bg=#333333 fg=#5eacd3'
setw -g window-status-current-style 'fg=lightgray bold bg=#5091b2'
setw -g window-status-current-format ' #I #W #F '
setw -g window-status-format ' #I #W #[fg=yellow]#F '
set -g message-style 'fg=yellow bg=red bold'

set-option -g display-time 4000


bind r {
    source-file ~/.tmux.conf
    display-message -d 500 "Reloaded!"
}

set -g base-index 1
set -g mouse on
set -s escape-time 0
set -g status-left-length 35
set-option -g set-clipboard external

# copy mode
set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y {
    %if selection_present
        send-keys -X copy-pipe-and-cancel 'pbcopy'
    %else
        switch-client -T yank-mode
    %endif
}
set -g @my-word-separators "!\"#$%&'()*+,-./:;<=>?@[\\]^`{|}~"
set -g word-separators "#{@my-word-separators}"

# open first link in last terminal command
bind C-w {
    copy-mode
    send -X search-backward-text "$"
    send -X search-again
    send -X search-forward "https*://"
    send o
}

# open link in copy mode
bind -T copy-mode-vi o {
    set -p word-separators ""
    send-keys -X select-word
    send-keys -X copy-pipe-and-cancel 'xargs open'
    set -pF word-separators "#{@my-word-separators}"
}

# Fake text object commands
bind -T copy-mode-vi i {
    send-keys -X cancel-selection
    switch-client -T in-mode
}

bind -T in-mode w send-keys -X select-word
bind -T in-mode W {
    set -p word-separators ""
    send-keys -X select-word
    set -pF word-separators "#{@my-word-separators}"
}

bind -T in-mode b {
    send -X jump-to-backward '('
    send -X begin-selection
    send -X jump-to-forward ')'
}

bind -T in-mode B {
    send -X jump-to-backward '{'
    send -X begin-selection
    send -X jump-to-forward '}'
}

bind -T in-mode '"' {
    send -X jump-to-backward '"'
    send -X begin-selection
    send -X jump-to-forward '"'
}

bind -T in-mode "'" {
    send -X jump-to-backward "'"
    send -X begin-selection
    send -X jump-to-forward "'"
}

# Fake text object commands for direct yanking
bind -T yank-mode i switch-client -T yank-in-mode

bind -T yank-in-mode w {
    send-keys -X select-word
    send-keys -X copy-pipe-and-cancel 'pbcopy'
}
bind -T yank-in-mode W {
    set -p word-separators ""
    send-keys -X select-word
    set -pF word-separators "#{@my-word-separators}"
    send-keys -X copy-pipe-and-cancel 'pbcopy'
}

bind -T yank-in-mode b {
    send -X jump-to-backward '('
    send -X begin-selection
    send -X jump-to-forward ')'
    send-keys -X copy-pipe-and-cancel 'pbcopy'
}

bind -T yank-in-mode B {
    send -X jump-to-backward '{'
    send -X begin-selection
    send -X jump-to-forward '}'
    send-keys -X copy-pipe-and-cancel 'pbcopy'
}

bind -T yank-in-mode '"' {
    send -X jump-to-backward '"'
    send -X begin-selection
    send -X jump-to-forward '"'
    send-keys -X copy-pipe-and-cancel 'pbcopy'
}

bind -T yank-in-mode "'" {
    send -X jump-to-backward "'"
    send -X begin-selection
    send -X jump-to-forward "'"
    send-keys -X copy-pipe-and-cancel 'pbcopy'
}

# vim-like pane switching
bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

bind -r f run-shell "tmux neww ~/.local/bin/tmux-sessionizer"

# tmux-harpoon

# add current session
bind a run 'harpoon -a'
# add current pane
# bind A run 'harpoon -A'
# list sessions
# bind e run 'harpoon -l'
# edit sesions
bind e run 'harpoon -e'
bind h run 'harpoon -s 1'
bind j run 'harpoon -s 2'
bind k run 'harpoon -s 3'
bind l run 'harpoon -s 4'
bind C-h run 'harpoon -r 1'
bind C-j run 'harpoon -r 2'
bind C-k run 'harpoon -r 3'
bind C-l run 'harpoon -r 4'
